import { Check, TrendingUp, Users, Zap, Eye } from "lucide-react";
import creatorSample from "@/assets/creator-sample.jpg";
import lifestyleSample from "@/assets/lifestyle-sample.jpg";
import fanContentSample from "@/assets/fan-content-sample.jpg";

const stats = [
  { label: "TikTok Views in 30 Days", value: "+1.2M", icon: Eye },
  { label: "New Followers", value: "+18K", icon: Users },
  { label: "Fan Subscription Growth", value: "+2.7x", icon: TrendingUp },
  { label: "Engagement Increase", value: "+340%", icon: Zap },
];

const features = [
  "Hyper-realistic AI creators",
  "Natural voice and motion",
  "Platform-optimized formats",
  "Authentic lifestyle content",
  "UGC that brands actually pay for",
];

const WhySection = () => {
  return (
    <section className="py-24 px-4">
      <div className="max-w-6xl mx-auto">
        <p className="text-sm text-primary font-medium mb-3 text-center">Why Kuba Creators</p>
        <h2 className="text-3xl md:text-5xl font-bold text-center mb-4 text-foreground">
          Unlimited content types. One AI creator.
        </h2>
        <p className="text-muted-foreground text-center mb-16 max-w-2xl mx-auto">
          From UGC and product reviews to lifestyle vlogs and exclusive fan content. Your AI creator does it all.
        </p>

        {/* Content type cards */}
        <div className="grid md:grid-cols-3 gap-6 mb-16">
          {[
            { title: "UGC content at scale", img: creatorSample },
            { title: "Lifestyle & vlogs on autopilot", img: lifestyleSample },
            { title: "Exclusive fan content", img: fanContentSample },
          ].map((card) => (
            <div key={card.title} className="glass-card rounded-2xl overflow-hidden group">
              <div className="aspect-[4/5] overflow-hidden">
                <img
                  src={card.img}
                  alt={card.title}
                  loading="lazy"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                />
              </div>
              <div className="p-5">
                <h3 className="font-semibold text-foreground">{card.title}</h3>
              </div>
            </div>
          ))}
        </div>

        {/* Revenue stats */}
        <div className="glass-card rounded-2xl p-8 mb-8">
          <h3 className="text-xl font-bold mb-2 text-foreground">Projected Revenue Increase</h3>
          <p className="text-muted-foreground text-sm mb-6">
            Estimate the potential income generated by automated content systems.
          </p>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-6 text-sm">
            <div>
              <span className="text-muted-foreground">Short-form content</span>
              <p className="text-primary font-bold text-lg">+$3,200/mo</p>
            </div>
            <div>
              <span className="text-muted-foreground">Subscriber conversions</span>
              <p className="text-primary font-bold text-lg">+41%</p>
            </div>
            <div>
              <span className="text-muted-foreground">Content output</span>
              <p className="text-primary font-bold text-lg">3.6x /week</p>
            </div>
          </div>
        </div>

        {/* AI Content + Growth Results */}
        <div className="grid md:grid-cols-2 gap-6">
          <div className="glass-card rounded-2xl p-8">
            <h3 className="text-xl font-bold mb-2 text-foreground">AI-Generated Content That Doesn't Look AI</h3>
            <p className="text-muted-foreground text-sm mb-6">
              Our AI produces creator-style videos that feel real, engaging, and optimized for social algorithms.
            </p>
            <ul className="space-y-3">
              {features.map((f) => (
                <li key={f} className="flex items-center gap-3 text-sm text-secondary-foreground">
                  <Check className="w-4 h-4 text-primary flex-shrink-0" />
                  {f}
                </li>
              ))}
            </ul>
          </div>

          <div className="glass-card rounded-2xl p-8">
            <h3 className="text-xl font-bold mb-2 text-foreground">Creator Growth Results</h3>
            <p className="text-muted-foreground text-sm mb-6">
              We help you scale your own AI Influencer content and audience faster.
            </p>
            <div className="grid grid-cols-2 gap-6">
              {stats.map((s) => (
                <div key={s.label}>
                  <p className="text-2xl font-bold text-primary">{s.value}</p>
                  <p className="text-xs text-muted-foreground mt-1">{s.label}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default WhySection;
